# Generated by Django 4.0.6 on 2022-08-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_firstname_persons_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='apellido',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='nombre',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='localidad',
            new_name='location',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.persons')),
            ],
        ),
    ]
