# Generated by Django 4.0.6 on 2022-08-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_direccion_persons_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=255)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.administrators')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id_post', models.IntegerField(primary_key=True, serialize=False)),
                ('name_post', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('section', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=255)),
                ('reactions', models.IntegerField()),
                ('references', models.IntegerField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.administrators')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.areas')),
            ],
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
