# Generated by Django 4.0.6 on 2022-08-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_administrators_areas_posts_delete_administrator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
    ]
