# Generated by Django 4.0.6 on 2022-08-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_member_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrators',
            new_name='Administrator',
        ),
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
